database:
  databaseName: mongolocal
  dabaseURI: 127.0.0.1
  dabasePort: 12345
  dabaseVersion: 3.4.1
  initialLoadingFile: db/mongeez_local.xml

---

spring:
  profiles: prod
database:
  databaseName: finerleague
  dabaseURI: 127.0.0.1
  dabasePort: 12345
  userName: prodUser
  password: prodPassword
  initialLoadingFile: db/mongeez_local.xml